book_share/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include('users.urls')),
    path('',include('content.urls')),

]

content/urls.py
from django.urls import path
from . import views


app_name = 'content'
urlpatterns = [
    path('',views.index, name='index'),
    path('titles/',views.titles, name='titles'),
    path('titles/<int:title_id>/',views.book,name='book'),
    path('new_book/',views.new_book, name='new_book'),
    path('new_entry/<int:title_id>/',views.new_entry, name='new_entry'),
    path('edit_title/<int:title_id>/',views.edit_title,name='edit_title'),
    path('edit_entry/<int:entry_id>/',views.edit_entry,name='edit_entry'),
    path('delete_title/<int:title_id>/',views.delete_title, name='delete_title'),
    path('delete_entry/<int:entry_id>/',views.delete_entry, name='delete_entry'),
    path('search/',views.Search.as_view(),name='search'),
    path('add_or_remove_favorite/<int:title_id>/',views.add_or_remove_favorite, name='add_or_remove_favorite'),
    path('my_favorite',views.my_favorite, name='my_favorite'),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    path('',include('django.contrib.auth.urls')),
    path('register/',views.register, name='register'),
]

content/models.py
from django.db import models
from django.contrib.auth.models import User

class Title(models.Model):
    """titles of books"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    public = models.BooleanField(default=False)
    favorite = models.ManyToManyField(User, related_name='favorite',blank=True)


    def __str__(self):
        """return the string of the title"""

        return f'{self.text}\t————from user "{self.owner}"'

class Entry(models.Model):
    """entries of the books"""
    title = models.ForeignKey(Title, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)


    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        if len(self.text) <= 50:
            return self.text
        else:
            return f'{self.text[:50]}...'

content/forms.py
from django import forms
from .models import Title,Entry

class TitleForm(forms.ModelForm):
    class Meta:
        model = Title
        fields = ['text','public']
        labels = {'text':''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text':''}
        widgets = {'text': forms.Textarea(attrs={'cols':80})}

content/views.py
from django.shortcuts import render, redirect
from .models import Title,Entry
from .forms import TitleForm,EntryForm
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q


# <---- Below help manage database ---->
def sort_material(request):
    public_display_titles = []
    user_titles = Title.objects.filter(owner=request.user).order_by('date_added')
    user_private_titles = Title.objects.filter(owner=request.user, public=False)
    public_titles = Title.objects.filter(public=True).order_by('date_added')
    for title in public_titles:
        if title not in user_titles:
            public_display_titles.append(title)

    return user_titles, public_display_titles, user_private_titles

def title_expression(title,public_display_titles,user_titles, user_private_titles):
    if title in public_display_titles:
        read_only = True
        user_exp = '--(Read Only)--'
        return read_only,user_exp
    elif title in user_titles:
        if title not in user_private_titles:
            read_only = False
            user_exp = '--(Yourself【public】)--'
            return read_only, user_exp
        else:
            read_only = False
            user_exp = '--(Yourself【private】)--'
            return read_only, user_exp
    elif title not in private_titles or public_display_titles:
        raise Http404
# <---- Above help manage database ---->


def index(request):
    """home page"""
    return render(request, 'content/index.html')

@login_required
def titles(request):
    user_titles, public_display_titles, user_private_titles = sort_material(request)


    context = {'public_display_titles':public_display_titles,'user_titles':user_titles,}
    return render(request,'content/titles.html',context)

@login_required
def book(request,title_id):
    user_titles, public_display_titles, user_private_titles = sort_material(request)

    title = Title.objects.get(id=title_id)

    read_only, user_exp = title_expression(title,public_display_titles,user_titles,user_private_titles)

    is_favorite = False
    if title.favorite.filter(id=request.user.id).exists():
        is_favorite = True

    entries = title.entry_set.order_by('-date_added')
    context = {'title':title,'entries':entries,'user_exp':user_exp,'read_only':read_only,'is_favorite':is_favorite,
               'title.id':title.id}
    return render(request, 'content/book.html',context)

@login_required
def new_book(request):
    if request.method != 'POST':
        form = TitleForm()
    else:
        form = TitleForm(data=request.POST)
        if form.is_valid():
            new_book = form.save(commit=False)
            new_book.owner = request.user
            new_book.save()
            return redirect('content:titles')
    context = {'form':form}
    return render(request,'content/new_book.html',context)

@login_required
def new_entry(request,title_id):
    title = Title.objects.get(id=title_id)

    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.owner = request.user
            new_entry.title = title
            new_entry.save()
            return redirect('content:book',title_id=title_id)

    context = {'title':title,'form':form}
    return render(request,'content/new_entry.html',context)

@login_required
def edit_title(request, title_id):
    title = Title.objects.get(id=title_id)
    if title.owner != request.user:
        raise Http404

    if request.method != "POST":
        form = TitleForm(instance=title)
    else:
        form = TitleForm(instance=title,data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('content:book',title_id=title.id)

    context = {'title':title, 'form':form}
    return render(request,'content/edit_title.html',context)

@login_required
def edit_entry(request,entry_id):
    entry = Entry.objects.get(id=entry_id)
    title = entry.title
    if title.owner != request.user:
        raise Http404

    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry,data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('content:book',title_id=title.id)
    context = {'entry':entry,'title':title,'form':form}
    return render(request,'content/edit_entry.html',context)

@login_required
def delete_title(request, title_id):
    title = Title.objects.get(id=title_id)
    if title.owner != request.user:
        raise Http404

    if request.method == 'POST':
        title.delete()
        return redirect('content:titles')

    context = {'title':title}
    return render(request,'content/delete_title.html',context)

@login_required
def delete_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    title = entry.title
    if title.owner != request.user:
        raise Http404

    if request.method == 'POST':
        entry.delete()
        return redirect('content:book',title_id=title.id)

    context = {'title':title,'entry':entry}
    return render(request,'content/delete_entry.html',context)

@login_required
def add_or_remove_favorite(request, title_id):

    title = Title.objects.get(id=title_id)

    if title.favorite.filter(id=request.user.id).exists():
        title.favorite.remove(request.user)

    else:
        title.favorite.add(request.user)
    return redirect('content:book', title_id=title.id)

@login_required
def my_favorite(request):
    user = request.user
    my_favorite = user.favorite.all()

    context = {'my_favorite':my_favorite}
    return render(request, 'content/my_favorite.html', context)

class Search(LoginRequiredMixin,ListView):
    model = Title
    template_name = 'content/search.html'
    context_object_name = 'search_result_title'

    def get_queryset(self):
        user = self.request.user
        qs = super().get_queryset()
        query = self.request.GET.get('search')

        if query:
            search_result_title = qs.filter(text__icontains=query).filter(Q(owner=user)|Q(public=True)).distinct()
            return search_result_title
        else:
            return None

content/templates/content/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="'utf-8">
    <meta name="viewport" content="width-device-width, initial-scale=1,shrink-to-fit=no">
    <title>Book Share</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-0 py-0 border">

        <a class="navbar-brand" href="{% url 'content:index' %}">
            <div class="logo-image">
                <img src="https://imgtr.ee/images/2023/02/13/ObWsU.png" class="img-fluid">
            </div>
        </a>
        <a class="navbar navbar-brand navbar-light bg-dark" href="{% url 'content:index' %}">Book Share</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarCollapse" aria-controls="navbarCollapse"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="navbar navbar-secondary navbar-light bg-dark text-nowrap" href="{% url 'content:titles' %}">
                        &raquo;Check out Books&raquo;</a>
                </li>
            </ul>


            <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'content:search' %}" >
                {% csrf_token %}
                <input class="form-control mr-sm-3" type="search" name="search" placeholder="Search by title">
                <button class="btn btn btn-outline-info my-2 my-sm-0" type="submit"> Search </button>
            </form>

            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <span class="navbar-text text-nowrap" >Hello, {{ user.username }}.</span>
                    </li>
                    &nbsp;&nbsp;&nbsp;&nbsp;
                    <li class="nav-item">
                        <a class="nav-link text-nowrap" href="{% url 'users:logout' %}">Log out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                    </li>
                {% endif %}
            </ul>
        </div>

    </nav>
    <main role="main" class="container">
        <div class="p-3 mb-2 bg-light">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div class="pb-3 mb-2 bg-light">
            {% block content %}{% endblock content %}
        </div>
    </main>

</body>
</html>

content/templates/content/book.html
{% extends 'content/base.html' %}

{% block page_header %}
    <h3 style="nowrap">{{ title }}&nbsp;&nbsp;<small>
        <img style="display:inline" src="https://imgtr.ee/images/2023/02/21/R0OuQ.png">
        </small> X {{ title.favorite.count }}</h3>

    <h6>&raquo;&raquo;{{ user_exp }}&laquo;&laquo;</h6>


{% endblock page_header %}

{% block content %}
<div class="btn-group btn-group-lg btn-dark" role="group" aria-label="user_auth">
                <a href="{% url 'content:my_favorite' %}" class="btn btn-dark" >To my favorites &raquo;</a>
                <a href="{% url 'content:titles' %}" class="btn btn-dark" >Back to book list &raquo;</a>
                <a href="{% url 'content:index' %}" class="btn btn-dark" >Home page &raquo;</a>
            </div>

<br><br>
{% if read_only %}
    {% if is_favorite %}
        <a class="btn btn-lg btn-danger" href="{% url 'content:add_or_remove_favorite' title.id %}" role="button">
            Remove favorite</a>
    {% else %}
        <a class="btn btn-lg btn-success" href="{% url 'content:add_or_remove_favorite' title.id %}" role="button">
            Add to favorite</a>
    {% endif %}

    {% for entry in entries %}
        <div class="card mb-3">
            <h4 class="card-header">
                Posted at --{{ entry.date_added|date:'M d, Y H:i' }}

            </h4>
            <div class="card-body">
                {{ entry.text|linebreaks }}
            </div>
        </div>
    {% empty %}
        <p>There are no entries for this book yet.</p>
    {% endfor %}

{% else %}
    <a class="btn btn-lg btn-success" href="{% url 'content:new_entry' title.id %}" role="button">
        Add a new entry</a>
    {% for entry in entries %}
        <div class="card mb-3">
            <h4 class="card-header">
                Posted at --{{ entry.date_added|date:'M d, Y H:i' }}
                <small><a class="btn btn-warning" href="{% url 'content:edit_entry' entry.id %}"
                    role="button">Edit entry</a> </small>
                <small><a class="btn btn-danger" href="{% url 'content:delete_entry' entry.id %}
"                   role="button">Delete entry</a> </small>
            </h4>
            <div class="card-body">
                {{ entry.text|linebreaks }}
            </div>
        </div>
    {% empty %}
        <p>There are no entries for this book yet.</p>
    {% endfor %}
{% endif %}

<div class="btn-group btn-group-lg btn-dark" role="group" aria-label="user_auth">
    <a href="{% url 'content:my_favorite' %}" class="btn btn-dark" >To my favorites &raquo;</a>
    <a href="{% url 'content:titles' %}" class="btn btn-dark" >Back to book list &raquo;</a>
    <a href="{% url 'content:index' %}" class="btn btn-dark" >Home page &raquo;</a>
</div>

{% endblock content %}

content/templates/content/delete_entry.html
{% extends 'content/base.html' %}
{% load bootstrap4 %}

{% block page_header %}
    <h1>Are you sure you want to delete this note?</h1>
    <h4 class="text-danger">It cannot be undone.</h4>
{% endblock page_header %}

{% block content %}

    <form method="post">
        {% csrf_token %}
        {% buttons %}
            <button name="submit" class="btn btn-lg btn-danger">Confirm Delete</button>
        {% endbuttons %}

         <input type="hidden" name="next" value="{% url 'content:book' title.id %}" />
    </form>

    <a class="btn btn-lg btn-dark" href="{% url 'content:book' title.id %}">Cancel</a>
{% endblock content %}

content/templates/content/delete_title.html
{% extends 'content/base.html' %}
{% load bootstrap4 %}

{% block page_header %}
    <h1>Are you sure you want to delete this book?</h1>
    <h4 class="text-danger">This would include any entries under this book title. It cannot be undone.</h4>
{% endblock page_header %}

{% block content %}

    <form method="post">
        {% csrf_token %}
        {% buttons %}
            <button name="submit" class="btn btn-lg btn-danger">Confirm Delete</button>
        {% endbuttons %}

         <input type="hidden" name="next" value="{% url 'content:titles' %}" />
    </form>

    <a class="btn btn-lg btn-dark" href="{% url 'content:titles' %}">Cancel</a>

{% endblock content %}

content/templates/content/edit_entry.html
{% extends 'content/base.html' %}
{% load bootstrap4 %}

{% block page_header %}
    <p><a href="{% url 'content:book' title.id%}">{{ book }}</a></p>

    <h1>Edit entry:</h1>
{% endblock page_header %}

{% block content %}

    <form method="post" action="{% url 'content:edit_entry' entry.id %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-warning">Change</button>
        {% endbuttons %}

        <input type="hidden" name="next" value="{% url 'content:book' title.id %}" />
    </form>

    <a class="btn btn-lg btn-dark" href="{% url 'content:book' title.id %}">Go back &raquo;</a>
{% endblock content %}

content/templates/content/edit_title.html
{% extends 'content/base.html' %}
{% load bootstrap4 %}

{% block page_header %}
    <h1>Edit title:</h1>
{% endblock page_header %}

{% block content %}

    <form method="post" action="{% url 'content:edit_title' title.id %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        <div class="form-check">
            <input class="form-check-input" type="checkbox" value=True id="public" hidden="hidden"/>
            <label class="form-check-label" for="public">Make post public?</label>

        </div>
        <br>
        {% buttons %}
            <button name="submit" class="btn btn-warning">Change</button>
        {% endbuttons %}

        <input type="hidden" name="next" value="{% url 'content:titles' %}" />
    </form>

    <a class="btn btn-lg btn-dark" href="{% url 'content:titles' %}">Go back &raquo;</a>
{% endblock content %}

content/templates/content/index.html
{% extends 'content/base.html' %}

{% block page_header %}
    <div class="jumbotron">
        <h1 class="display-3">Share your reading insights.<small><span class="badge badge-info">Beta</span></small></h1>
        <p class="lead">Reading is the process of intellectual collisions. Make a mark of those sparks
            by noting them here!</p>
        {% if user.is_authenticated == False %}
            <div class="btn-group btn-group-lg btn-dark" role="group" aria-label="user_auth">
                <a href="{% url 'users:register' %}" class="btn btn-dark" >Register &raquo;</a>
                <a href="{% url 'users:login' %}" class="btn btn-dark" >Log in &raquo;</a>
            </div>
        {% else %}

            <div class="btn-group btn-group-lg btn-dark" role="group" aria-label="to_content">
                <a href="{% url 'content:titles' %}" class="btn btn-dark" >Let's go &raquo;</a>
                <a href="{% url 'content:my_favorite' %}" class="btn btn-dark" >My favorites &raquo;</a>
            </div>
        {% endif %}

    </div>

    <div id="index" class="carousel slide">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#index" data-slide-to="0" class="active"></li>
            <li data-target="#index" data-slide-to="1"></li>
            <li data-target="#index" data-slide-to="2"></li>
        </ol>
        <!--/.Indicators-->
        <!--Slides-->
        <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
                <img class="d-block w-100" src="https://imgtr.ee/images/2023/02/13/Obdzl.jpg" alt="b1">
                <div class="carousel-caption d-none d-md-block">
                    <h2 class="text-dark">Help you fall in love with reading!</h2>
                </div>

            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="https://imgtr.ee/images/2023/02/13/ObmWV.jpg" alt="b2">
                <div class="carousel-caption d-none d-md-block">

                    <h2 class="text-light">Pick up a book and never want to let it go!</h2>

                </div>

            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="https://imgtr.ee/images/2023/02/13/ObZ1X.jpg" alt="b3">
                <div class="carousel-caption d-none d-md-block">

                    <h2 class="text-dark">Gain knowledge and growth!</h2>

                </div>

            </div>
        </div>

        <a class="carousel-control-prev" href="#index" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#index" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

{% endblock page_header %}

content/templates/content/my_favorite.html
{% extends 'content/base.html' %}
{% load bootstrap4 %}

{% block page_header %}
    <h1>Favorite collection:</h1>

{% endblock page_header %}

{% block content %}

<a class="btn btn-lg btn-dark" href="{% url 'content:index' %}" role="button">Home Page &raquo;</a>


<div class="jumbotron">


    <h3 class="text-info">Here are books you have collected:</h3>
    <ul>
        {% for title in my_favorite %}
            <li><h3>
                <a class="font-italic" href="{% url 'content:book' title.id %}">{{ title }}&nbsp;&nbsp;
                    <small><img style="display:inline" src="https://imgtr.ee/images/2023/02/21/R0OuQ.png">
                     X {{ title.favorite.count }}</small></a>
            </h3></li>
        {% empty %}
            <li><h5 class="text-info">No books has been publicly posted by others yet either.</h5></li>
        {% endfor %}
    </ul>
</div>

<br><br><a class="btn btn-lg btn-dark" href="{% url 'content:index' %}" role="button">Home Page &raquo;</a>


{% endblock content %}

content/templates/content/new_book.html
{% extends 'content/base.html' %}
{% load bootstrap4 %}

{% block page_header %}
    <h1>Add a new book:</h1>
{% endblock page_header %}

{% block content %}

    <p>Do you want this post to be seen by all users? If so, check "Public".</p>
    <form method='post' action="{% url 'content:new_book' %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        <div class="form-check">
            <input class="form-check-input" type="checkbox" value=True id="public" hidden="hidden"/>
            <label class="form-check-label" for="public">Make post public?</label>

        </div>
        <br>
        {% buttons %}
            <button name="submit" class="btn btn-success">Add</button>
        {% endbuttons %}
    </form>

    <a class="btn btn-lg btn-dark" href="{% url 'content:titles' %}">Go back &raquo;</a>



{% endblock content %}

content/templates/content/new_entry.html
{% extends 'content/base.html' %}
{% load bootstrap4 %}

{% block page_header %}
    <h1>Add new entry:</h1>
{% endblock page_header %}

{% block content %}

    <form method="post" action="{% url 'content:new_entry' title.id %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-success">Add</button>
        {% endbuttons %}

        <input type="hidden" name="next" value="{% url 'content:book' title.id %}" />
    </form>

    <a class="btn btn-lg btn-dark" href="{% url 'content:book' title.id %}">Go back &raquo;</a>
{% endblock content %}

content/templates/content/search.html
{% extends 'content/base.html' %}
{% load bootstrap4 %}

{% block page_header %}
    <h2 class="text-info">Search suggestions:</h2>
<h5 class="text-info">--Must input keywords, otherwise no search result will be displayed.</h5>
    <h5 class="text-info">--Try more accurate keywords to find the book you are looking for.</h5>

{% endblock page_header %}

{% block content %}
<h2 class="text-info">&nbsp;Here are the search results by title:</h2>
<ul>

    {% for title in search_result_title %}

        <li><h3>
            <a class="font-italic" href="{% url 'content:book' title.id %}">{{title}}</a>
        </h3></li>
    {% empty %}
        <li><p class="text-info">No book matches your search.</p></li>
    {% endfor %}
</ul>


<a class="btn btn-lg btn-dark" href="{% url 'content:titles' %}" role="button">Go back &raquo;</a>



{% endblock content %}

content/templates/content/titles.html
{% extends 'content/base.html' %}
{% load bootstrap4 %}

{% block page_header %}
    <h1>Books</h1>
    <h5 class="text-info">--You can access books posted as public content by other users, but in "read only" mode.</h5>
    <h5 class="text-info">--All books below are sorted according to post time.</h5>
    <h5 class="text-info">--Too many items below? Try searching by title.</h5>
{% endblock page_header %}

{% block content %}
<a class="btn btn-lg btn-success" href="{% url 'content:new_book' %}" role="button">Add a new book</a>
<br><br><a class="btn btn-lg btn-dark" href="{% url 'content:index' %}" role="button">Home Page &raquo;</a>
<br><br>

<div class="jumbotron">
    <h4 class="text-info">Here are the books you have posted:</h4>

    <ul>
        {% for title in user_titles %}
            <li><h3>
                <a class="font-italic" href="{% url 'content:book' title.id %}">{{ title }}&nbsp;&nbsp;
                    <small><img style="display:inline" src="https://imgtr.ee/images/2023/02/21/R0OuQ.png">
                     X {{ title.favorite.count }}</small></a>
                    <small><a class="btn btn-warning" href="{% url 'content:edit_title' title.id %}"
                              role="button">Edit title</a></small>
                    <small><a class="btn btn-danger" href="{% url 'content:delete_title' title.id %}"
                              role="button">Delete title</a></small>
                </a>
            </h3></li>
        {% empty %}
            <li><h5 class="text-info">You have not added any books yet, but check out publicly posted books by others.</h5></li>
        {% endfor %}
    </ul>

    <hr class="my-4">

    <h3 class="text-info">Here are books publicly posted by other users:</h3>
    <ul>
        {% for title in public_display_titles %}
            <li><h3>
                <a class="font-italic" href="{% url 'content:book' title.id %}">{{ title }}&nbsp;&nbsp;
                    <small><img style="display:inline" src="https://imgtr.ee/images/2023/02/21/R0OuQ.png">
                     X {{ title.favorite.count }}</small></a>
            </h3></li>
        {% empty %}
            <li><h5 class="text-info">No books has been publicly posted by others yet either.</h5></li>
        {% endfor %}
    </ul>
</div>

<br><br><a class="btn btn-lg btn-dark" href="{% url 'content:index' %}" role="button">Home Page &raquo;</a>


{% endblock content %}